export const AGENT_DEFINITIONS = Object.freeze([
  Object.freeze({
    key: 'professor',
    displayName: 'Professor',
    role: 'Builder',
    description: 'Plans and implements code changes.',
    discordId: '1518980056880517140',
    botUser: 'lihsheng-professor[bot]',
    pollEnabled: true,
    lifecycleControl: 'disabled',
    service: 'opencode-professor',
    configName: 'opencode-professor',
    containerName: 'openab-opencode-professor',
    backend: 'opencode',
    image: 'ghcr.io/openabdev/openab-opencode:latest',
    dataDir: 'data/agents/opencode-professor',
    desiredState: 'unmanaged',
  }),
  Object.freeze({
    key: 'berlin',
    displayName: 'Berlin',
    role: 'Reviewer',
    description: 'Reviews pull requests and reports risks.',
    discordId: '1518983231012208903',
    botUser: 'lihsheng-berlin[bot]',
    pollEnabled: true,
    lifecycleControl: 'disabled',
    service: 'opencode-1',
    configName: 'opencode-1',
    containerName: 'openab-opencode-1',
    backend: 'opencode',
    image: 'ghcr.io/openabdev/openab-opencode:latest',
    dataDir: 'data/agents/opencode-1',
    desiredState: 'unmanaged',
  }),
  Object.freeze({
    key: 'tokyo',
    displayName: 'Tokyo',
    role: 'Verifier',
    description: 'Validates fixes and regression coverage.',
    discordId: '1518982568920355017',
    botUser: 'lihsheng-tokyo[bot]',
    pollEnabled: true,
    lifecycleControl: 'disabled',
    service: 'opencode-2',
    configName: 'opencode-2',
    containerName: 'openab-opencode-2',
    backend: 'opencode',
    image: 'ghcr.io/openabdev/openab-opencode:latest',
    dataDir: 'data/agents/opencode-2',
    desiredState: 'unmanaged',
  }),
  Object.freeze({
    key: 'gemini',
    displayName: 'Gemini',
    role: 'Researcher',
    description: 'Handles research and conversational tasks.',
    discordId: null,
    botUser: null,
    pollEnabled: false,
    lifecycleControl: 'guarded-test',
    service: 'gemini',
    configName: 'gemini',
    containerName: 'openab-gemini',
    backend: 'gemini',
    image: 'ghcr.io/openabdev/openab-gemini:latest',
    dataDir: 'data/agents/gemini',
    desiredState: 'unmanaged',
  }),
]);

export function getAgentDefinition(key) {
  return AGENT_DEFINITIONS.find((definition) => definition.key === key) || null;
}
